### ISSUE TITLE
How to access the first assignment and the second assignment?

### ISSUE THREAD

**Issue by zouzy5137** [turnaround5954/Homework-CPP#1]
Hello, my friend! I am new to CS106L and I'm trying to do assignment 1 and assignment 2.
However, when I follow the guide to setup assignments, I find that in the "Assignment Setup" part of the course website, it requires me to do this command: "ssh [yourSUIDHere@myth.stanford.edu](mailto:yourSUIDHere@myth.stanford.edu)".
Does that mean if I am not a Stanford student, I cannot do those two assignments?😥😥
How did you setup those assignments?
The link is here [http://web.stanford.edu/class/cs106l/assignment-setup](url)

**Comment by turnaround5954** [comment]
u don't have to follow all the commands.
u just need to build the project yourself on your own machine. (follow the rest of the guide)
the command "ssh xxx" simply says: "connect to stanford's remote machine" and of course you don't have to do that.

> Hello, my friend! I am new to CS106L and I'm trying to do assignment 1 and assignment 2. However, when I follow the guide to setup assignments, I find that in the "Assignment Setup" part of the course website, it requires me to do this command: "ssh [yourSUIDHere@myth.stanford.edu](mailto:yourSUIDHere@myth.stanford.edu)". Does that mean if I am not a Stanford student, I cannot do those two assignments?😥😥 How did you setup those assignments? The link is here [http://web.stanford.edu/class/cs106l/assignment-setup](url)
